# fly.toml app configuration file generated for notification-microservice on 2024-12-31T22:50:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notification-microservice'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 9292
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 8
